### ISSUE TITLE
Spike: Investigate issues releasing with npm5 in regards to package-lock.json files.

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#10]
# Issue Description
When we were working on releasing v2.0.0, we ran into the following error when running the release script.

```
npm ERR! code 1
npm ERR! Command failed: git add /Users/rm012685/release/terra-toolkit/package-lock.json
npm ERR! The following paths are ignored by one of your .gitignore files:
npm ERR! package-lock.json
npm ERR! Use -f if you really want to add them.
npm ERR! 
```

It would be good to figure out what the release script is trying to add an ignored file to our version control so we can use the latest version of npm to release without issues.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Running the release script with npm 5 completes successfully

**Comment by emilyrohrbough** [comment]
I wonder if adding [this file](https://github.com/cerner/terra-core/blob/master/.npmrc) would resolve this issue.

**Comment by mjhenkes** [comment]
Or we could check package-lock.json into source control.

**Comment by emilyrohrbough** [comment]
@mjhenkes is this resolved? In this PR, the package-lock was updated  https://github.com/cerner/terra-toolkit/pull/42/files#diff-32607347f8126e6534ebc7ebaec4853dR407

**Comment by mjhenkes** [comment]
@emilyrohrbough yes, i think so.
