### ISSUE TITLE
Webpack shareable config is not generating -webkit-flex styles

### ISSUE THREAD

**Issue by nagrawal3** [cerner/terra-toolkit#110]
# Issue Description

CSS files generated through webpack by utilizing shareable webpack config provided by terra doesn't have -webkit-flex styles.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

CSS generated should have -webkit-flex styles.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version: terra-toolkit 3.4.0
* Browser Name and Version: PhantomJS
* Operating System and version (desktop or mobile):

**Comment by nagrawal3** [comment]
Temporary fix: update plugins to include Autoprefixer plugin like below:

```
Autoprefixer({
  browsers: [
    'iOS >= 10',
    'last 2 and_chr versions',
    'last 2 android versions',
    'last 2 chrome versions',
    'last 2 edge versions',
    'last 2 firefox versions',
    'last 2 ie versions',
    'last 2 safari versions',
    'safari 8',
  ],
})
```

'safari 8' in Autoprefixer will create styles corresponding to -webkit-flex

**Comment by emilyrohrbough** [comment]
We should look into opening the default webpack configuration to use `env.browserslist`. We could either provide a path to the browserslist config to load or take an array of browser queries.

**Comment by emilyrohrbough** [comment]
Autoprefixer does not recommend passing a browserslist directly but instead states:
> The best way to provide browsers is a .browserslistrc file in your project root, or by adding a browserslist key to your package.json.

This will allow other build tools to utilize the same browserslist as the webpack.
