### ISSUE TITLE
Disable css-loader minimize option, uses buggy version of cssnano that breaks themes

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#121]
# Issue Description
In the current version of css-loader, if you run webpack in production mode, it will minimize the CSS with cssnano v3. The version of [cssnano included as a dependency](https://github.com/webpack-contrib/css-loader/blob/master/package.json#L18) in css loader [includes a bug](https://github.com/cssnano/cssnano/issues/450) which impacts long-hand CSS properties using CSS custom properties. A fix has supposedly been landed in cssnano v4-rc.2 release (need to test), but that release hasn't made it's way back into css-loader.

We don't see the issue in our default style, the issue is only present when setting values for CSS custom properties that are used in long-hand CSS styles

For example, given the following themable variables:

```css
:root {
    --terra-form-radio-outer-ring-border-style: solid;
    --terra-form-radio-focus-border-color: #88a8ef;
    --terra-form-radio-focus-border-width: 2px;
}
```

We get output incorrectly as the following from cssnano:

```css
:root {
  border: 2px solid #88a8ef;
}
```

### Attempted fix
We've got around this before by converting the source code to short-hand. This way cssnano doesn't do any conversion on the style.

e.g `border: var(--border-style, 1px solid #f00);`

### Sub issue
However, this causes a problem with styles that could be bidirectional.

For example, we break out padding and margin into individual styles for bidi reasons.

```css
   padding-bottom: var(--terra-tag-padding-bottom, 0.1428rem);
   padding-left: var(--terra-tag-padding-left, 0.5rem);
   padding-right: var(--terra-tag-padding-right, 0.5rem);
   padding-top: var(--terra-tag-padding-top, 0.1428rem);
```
This seems to make it easier for the postcss-rtl plugin to apply `[dir="ltr"]` and `[dir="rtl"]` selectors to the left and right padding.

It seems like we've run into issues in the past with setting padding to use short-hand property syntax and bidi styling like below:

```css
padding: var(--terra-select-padding-top, 0) var(--terra-select-padding-right, 0) var(--terra-select-padding-bottom, 0) var(--terra-select-padding-left, 0); 
```
My guess is the postcss-rtl plugin doesn't parse / understand the css custom property values or it may see the values are set to a nuetral, non-bidi necessary value like 0 and opt-out of creating `[dir="ltr"]` and `[dir="rtl"]` selectors. This is fine until someone themes one of the left or right padding values to be something other than 0, then there theme doesn't not work bidirectionaly.

@JakeLaCombe is likely more familiar with the details on the bidi styles issue.

### Proposal
I'd recommend we disable the `minimize` option in the css-loader to opt-out of cssnano behavior until css-loader updates to use cssnano v4.

Using the sass-loader, CSS is already minified when webpack is run in production mode. cssnano offers a more desctructive minimization that I don't find to be completely neccessary with our current webpack setup.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Theming styles work and theming and bidirectionality styling work together.

**Comment by mjhenkes** [comment]
The proposal makes sense to me, and will enable @emilyrohrbough to use the browser list updates she has been working on. cssnano also is locked into an old version of that.

**Comment by emilyrohrbough** [comment]
I think this proposal makes sense as a temporary solution to the multiple issues we have seen. @mjhenkes and I spent some time looking at other css minimize modules yesterday and it appears most modules are using cssnano and will experience the same issues.
