### ISSUE TITLE
Re-enable Minimize via css-loader

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-toolkit#122]
# Issue Description
Enable minimize option in css-loader.

Blocked by https://github.com/cssnano/cssnano/issues/408 then on the css-loader to consumer the v4 version.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Enable minimize option in css-loader, once the css-loader has been updated & released to use cssnano v4.

## Current Behavior
In the current version of css-loader (0.28), if you run webpack in production mode, it will minimize the CSS with cssnano v3. The version of cssnano included as a dependency in css loader includes a bug which impacts long-hand CSS properties using CSS custom properties. Additionally cssnano v3 used an outdated version of `autoprefixer` and `browserslist` which will be bumped in the next cssnano v4.

**Comment by bjankord** [comment]
[webpack css-loader v1](https://github.com/webpack-contrib/css-loader/releases/tag/v1.0.0) has been released which removed the `minimize` option. This means css-loader no-longer uses cssnano.

**Comment by emilyrohrbough** [comment]
Here was the suggestion for including minimization yourself

> use [postcss-loader](https://github.com/postcss/postcss-loader) with [cssnano](https://github.com/cssnano/cssnano) or use [optimize-cssnano-plugin](https://github.com/intervolga/optimize-cssnano-plugin) plugin
