### ISSUE TITLE
aggregate-translations: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dv297** [cerner/terra-toolkit#148]
# Bug Report

## Description
On Windows (not sure if it's Windows specific but I assume things have been working for the rest of the ecosystem), when running aggregate translations using the syntax specified in the doc for the aggregate-translations CLI, I get 

```
TypeError: Cannot read property 'split' of undefined
    at addCustomDirectory (C:\workspace\dv297_personal_repo\terra-toolkit\scripts\aggregate-translations\aggregate-translations-cli.js:12:35)
```

## Steps to Reproduce
0. Maybe run on Windows?
1. Add `"aggregate-translations": "tt-aggregate-translations -b ./ -d ./translations -l ['en','es'] -o ./aggregated-translations",` to NPM scripts
2. Run `npm run aggregate-translations`

## Expected Behavior
aggregated-translations directory is created

## Possible Solution
Terra-toolkit uses Commander for collecting its arguments. Not sure if something changed across versions or if it has inconsistent behavior across platforms, but when I logged out the params when running a local modified version of the CLI, I get this
// baseDirectory, searchPattern
./translations undefined

I assume the "baseDirectory" should be enough. At least when I just use that, the CLI runs fine.

## Environment

* Node/npm Version: 9.8.0/ 6.2.0
* Operating System and version (desktop or mobile): Windows 10

**Comment by emilyrohrbough** [comment]
Are you passing locales using the `--locales ` var?

**Comment by bjankord** [comment]
I'm able to reproduce this issue on a Mac with the steps provided. Created a reduced test case here: https://github.com/bjankord/aggregate-translations-cli-issue-repro

**Comment by bjankord** [comment]
Dropping the `baseDirectory` arg from the [addCustomDirectories function](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L10) seems to fix this.

```
const addCustomDirectory = (searchPattern) => {
  const customDir = searchPattern.split('/').join(path.sep);
  customSearchDirectories.push(customDir);
};
```
I want to check with @emilyrohrbough and see if there is any use case for the `baseDirectory` arg in that function, it doesn't look like it was being used for anything.
