### ISSUE TITLE
Update dependencies to latest stable release

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#161]
# Feature Request

## Description
Look through this list and see if we can update to latest stable releases of any dependencies we are behind on: https://david-dm.org/cerner/terra-toolkit

**Comment by noahbenham** [comment]
Would love to see `babel-loader` 8 pulled in so we can start using Babel 7 with Fragment support. I can work on this if you'd like @bjankord.

**Comment by noahbenham** [comment]
Looks like terra-dev-site may need to be updated at the same time. I've updated terra-toolkit to the latest babel version locally and I'm getting `Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".`

Is there a better way to construct these dependencies so ecosystem updates are smoother?

**Comment by bjankord** [comment]
We'll be discussing updating babel in our next terra lead sync. I know one of the things we've discussed is providing a shared babel-config similar to shared eslint, stylelint, browserslist configs. We'll need to cordinate the major release of terra-toolkit with the major release of some of our other projects like terra-dev-site. I'll post more on this issue as I figure out what direction we're going with the babel upgrade.

**Comment by noahbenham** [comment]
Do you have any updates on this @bjankord?

**Comment by bjankord** [comment]
No updates on this, it looks like we won't be getting to a major version bump of terra-toolkit until 2019 sometime. We're planning on slotting this into terra-toolkit v5.

**Comment by supreethmr** [comment]
Along with this dependency update, we would require to update Autoprefixer to latest version (version 9+) as this would resolve the prefixing issues that are affecting styles of terra-components on IE browser 

While closing this Issue we might need to remove some of vendor-specific style that has been added to [terra-form-input,](https://github.com/cerner/terra-core/blob/cbb90a3b6c88bffdf3fd345f319321a53b2704b9/packages/terra-form-input/src/Input.module.scss#L30) [terra-form-textarea](https://github.com/cerner/terra-core/blob/cbb90a3b6c88bffdf3fd345f319321a53b2704b9/packages/terra-form-textarea/src/Textarea.module.scss#L41) and [terra-form-select](https://github.com/cerner/terra-core/blob/cbb90a3b6c88bffdf3fd345f319321a53b2704b9/packages/terra-form-select/src/_Frame.module.scss#L233) as a part of fix to this issue : https://github.com/cerner/terra-core/issues/2198.
