### ISSUE TITLE
Allow tests using custom viewports to not be named according to terra viewports

### ISSUE THREAD

**Issue by Matthematic** [cerner/terra-toolkit#162]
# Feature Request

## Description
Currently terra-toolkit locks the screenshot folder names down to the names of terra viewports, even when you might not even be using terra viewports. This causes both inaccurate naming as using a viewport of { width: 558, height: 768 } will be named "Chrome_small", and also prevents the possibility of having the same screenshot name for multiple viewports since one will overwrite the other. We can uplift getFormFactor() to consider this and only return the name of a terra viewport on exact match, else return the custom name, else return the width.  

## Additional Context / Screenshots

Here is the function:

    function getFormFactor(context) {
    let formFactor = global.browser.options.formFactor;

    if (!formFactor) {
      const browserWidth = context.meta.viewport.width;
      const viewportSizes = Object.keys(VIEWPORTS);
      for (let i = 0; i < viewportSizes.length; i += 1) {
        const viewport = viewportSizes[i];
        if (browserWidth <= VIEWPORTS[viewport].width) {
          formFactor = VIEWPORTS[viewport].name;
          break;
        }
      }
    }
 
We could update it to be something like this:

    function getFormFactor(context) {
    let formFactor = global.browser.options.formFactor;

    if (!formFactor) {
      const browserWidth = context.meta.viewport.width;
      const viewportSizes = Object.keys(VIEWPORTS);
      for (let i = 0; i < viewportSizes.length; i += 1) {
        const viewport = viewportSizes[i];
        if (browserWidth === VIEWPORTS[viewport].width) {
          formFactor = VIEWPORTS[viewport].name;
          break;
        }
      }

      if (!formFactor && browserWidth <= VIEWPORTS[viewportSizes[viewportSizes.length-1]].width) {
        formFactor = `${context.meta.viewport.width}x${context.meta.viewport.height}`;
      }
    }

    // If viewport value is undefined due to being larger then the terra defiend viewports, set formFactor to enormous.
      formFactor = formFactor || 'enormous';

      return formFactor;
    }

**Comment by Matthematic** [comment]
Looking for second opinions on this.

**Comment by bjankord** [comment]
If you're using terra-toolkit, I'd recommend using the terra viewports. What's the use-case you have come across for not even be using terra viewports?

**Comment by Matthematic** [comment]
We are contributing to a project that defined their own breakpoints long ago and from what I've read it would be a large refactor to switch. I managed to get around my issue by manually appending a unique name, so if that's what I have to do until we refactor then I guess that's okay. Here is a relevant discussion about the breakpoints we currently have defined: https://github.cerner.com/ClinicalDev/clinical-timeline/issues/112

**Comment by emilyrohrbough** [comment]
Closing this issue. We only want to support Terra defined viewports and it possible to provide custom screenshots naming if custom viewports are desired.
