### ISSUE TITLE
Warning about requiring a peer of nightwatch despite terra-toolkit warning against using nightwatch

### ISSUE THREAD

**Issue by pc592** [cerner/terra-toolkit#165]
# Bug Report

## Description
After installing terra and dependencies, it was discovered that nightwatch introduced some vulnerabilities. [After seeing this warning in terra-toolkit's very own code](https://github.com/cerner/terra-toolkit/blob/bde3c9e047d6bfc18c2388ea7dcd3afc182e98f7/src/nightwatch/nightwatch.config.js#L14) we removed nightwatch and installed webdriver.io. However, running npm install at this point will give a warning that terra toolkit requires a peer of nightwatch.

## Steps to Reproduce
1. Install terra/terra-toolkit
2. See vulnerabilities. Remove nightwatch and replace with webdriver.io
3. npm install
4. See warning

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/22568286/45327868-fe022580-b51e-11e8-91c8-bf4bf419b559.png)

## Expected Behavior
No warnings for removing a package that terra-toolkit suggests we remove.

## Possible Solution
Not sure where that warning appears but perhaps check for webdriver.io and not have this warning if webdriver.io is installed.

## Environment

* Node/npm Version: Node >=4.x/npm 6.4.1
* Webpack Version: webpack 4.16.5
* Operating System and version (desktop or mobile): Windows

**Comment by bjankord** [comment]
The peerDependency on nightwatch will be removed in the next major version bump of toolkit.

**Comment by emilyrohrbough** [comment]
Branch: https://github.com/cerner/terra-toolkit/tree/toolkit-v5-remove-nightwatch
