### ISSUE TITLE
Add watch flag to tt-wdio

### ISSUE THREAD

**Issue by dv297** [cerner/terra-toolkit#166]
# Feature Request

## Description
I was thinking of ways to tighten the feedback loop when writing wdio tests. It currently takes ~1 minute and 45 seconds to run the CLI, running locally, find all the tests using the specified patterns, compile everything, and execute 6 basic assertions in one form factor. Although this is not unreasonable when just executing these tests, it can get a little unwieldy when first learning the framework, writing wdio tests the first time, and then realizing you have written the test incorrectly and have to redo this process multiple times.

Informal Time breakdown
* ~at 50 seconds before seeing anything appear in CLI, which then prints up to "[Terra-Toolkit:serve-static] Webpack compilation started"
* ~at 1:15, prints "Server started listening at port:8080"
* 6 assertions take 37 seconds.

The wdio CLI runner already accepts a --watch flag, which we could expose to tt-wdio. I've been looking into the scripts in this project and I'm not totally sure how much the watch flag would help, as I don't know enough about the wdio lifecycle to know what would and wouldn't run. If it just runs everything again when a file has been changed, it wouldn't be much help. But if it just executes the assertions on the files that were found on initial run of the file-search-pattern-match, it could possibly save on that ~50 seconds from above.

**Comment by emilyrohrbough** [comment]
@dv297 Are you wanted to see immediate output on the test execution? If so, the https://www.npmjs.com/package/wdio-spec-reporter offers immediate feedback. We opted out of included this package by default because it is slightly slower to continuous log to the console and is a lot of noise for large test runs.

**Comment by dv297** [comment]
I think wdio-spec-reporter is more for formatting how the specs look. It doesn't actually change how the tests are executed. What I'm really looking for is to reduce dead time when I'm writing tests. For example, if I'm writing my very first wdio test, my one and only assertion might take 5 seconds to execute. However, it takes 1 minute and 30 seconds to find all the test files in the project, compile the project, create the docker containers, start the static server, and then clean up after all that. I don't really want to hit that 1:30 cost every single time I try to introduce a change to my test. In an ideal environment, I might hit it one time, execute 5 second test, make change, excute 5 second test, rinse repeat until I'm happy with the tests, and then have some time for cleaning everything up.

**Comment by emilyrohrbough** [comment]
I don't recommend running tt-wdio for all locales and form factors if you are trying to learn how to run wdio tests. You can use webdriver's bin directly with `--watch` if desired. I am not familiar with this flag and haven't tested how it works. 

My recommendation for quickly running & rerunning tests (when not changing src code), would be to pack your site assets with webpack in production mode and then supply the build directory to your wdio.config.js with the `site` key. This will directly server your assets and remove compiling before tests start.
