### ISSUE TITLE
Remove nightwatch dependency

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#172]
# Feature Request

## Description
Remove nightwatch dependency

## Additional Context / Screenshots
We've deprecated the use of nightwatch and recommend users switch over to using webdriver.io tests. In our next major version bump of terra-toolkit, we plan on removing this dependency.

**Comment by emilyrohrbough** [comment]
Branch: https://github.com/cerner/terra-toolkit/tree/toolkit-v5-remove-nightwatch
