### ISSUE TITLE
Make translation import paths in generated files more explicit

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#174]
# Feature Request

## Description
When we write out the `translationsLoader.js` file via the aggregate-translation pre-build tool, it currently uses a require statement with [an implicit path](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/write-i18n-loaders.js#L16).

The generated code looks like:

```js
const loadArTranslations = (callback, scope) => {
  require.ensure([], (require) => {
    // eslint-disable-next-line
    const i18n = require('ar.js');
    callback.call(scope, i18n);
  }, 'ar-translations');
};
```

This type of import doesn't work with some webpack setups, specifically, create-react-app v2. By making the require path more explicit, adding `./` in from the of the file, it works better with specific webpack setups.

e.g.
```js
 require('./ar.js');

// instead of

 require('ar.js');
```

## Additional Context / Screenshots
Would there be any drawbacks to making this file path more explicit? None come to my mind when I thought through this change.

**Comment by emilyrohrbough** [comment]
LGTM. I can't think of any issues with this - however I don't think we could make this change in the default loaders because the aggregated translations wouldn't be in the same directory as the defaults.
