### ISSUE TITLE
Look for all translations in all the places

### ISSUE THREAD

**Issue by cody-dot-js** [cerner/terra-toolkit#206]
# Feature Request

## Description

I noticed that translations for consuming apps weren't being loaded properly: only the `terra-*` translations were loading. When diving into the [aggregatedTranslations script](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L10-L15), I noticed that the toolkit doesn't look in all places for translations.

In my application, the webpack config calls `aggregateTranslations` and relies on the default directory matchers. 

This matters for apps that consume other packages which follow the same pattern of placing custom translations under the `package-name/translations/` directory. 

E.g.: Public App A consumes Private App B which has custom translations. 
```
public_app_A
L translations (picked up properly)
  L en.json
  L ...
L node_modules
  L private_app_B
    L translations (not picked up)
      L en.json
      L ...
  L terra-*
    L translations (picked up properly)
      L en.json
      L ...
```

This aggregate-translations script, as it stands, won't pick up anything in node_modules/ except for terra translations. I believe that this is a common enough occurrence that multiple consumers will be affected and the aggregate-translations script should be used with as little config as possible to ease the barrier of developing apps.

## @ Mentions

@bjankord @JakeLaCombe

**Comment by cody-dot-js** [comment]
We have discussed a couple of things/possible solutions:

* include all translations by default (e.g. use `baseDir/**/translations`) matcher, but allow for an exclusion matcher as well
* leverage a webpack plugin that will perform a tree-shaking like transformation on the aggregated list and filter out any unused KVPs
  * first aggregate a list of all translations, then subtract from it all unused keys
* enhance the matcher to only search for [supported locales](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/i18nSupportedLocales.js#L1) json files under `**/translations/`
* namespace translations folders, e.g.: `app/cerner-i18n/` or `app/cerner-translations/`

**Comment by bjankord** [comment]
Currently, this can be resolved by passing `node_modules/private_app_B/translations` via the `directories` option to the aggregate-translations tool. This will add the `node_modules/private_app_B/translations` translation directory to the list of directories to look for translations in.

> include all translations by default (e.g. use baseDir/**/translations) matcher, but allow for an exclusion matcher as well

I believe this would require a major version bump, which I'm not opposed to. It is an inverse of what the functionality does today where one specifies which directories to look in. This would inverse that to specify which directories to exclude.

I'll bring this topic up in our next team sync and see about getting some more feedback on this.

**Comment by emilyrohrbough** [comment]
I support opening up translations by searching `baseDir/**/translations` with adding an `exclude` key which accepts an array of glob patterns. This would keep this passive.

**Comment by bjankord** [comment]
Discussed with the team, we're open to having aggregate translations look for translations in any directory in node_modules, not just terra packages.

Would need to change these lines here:
* https://github.com/cerner/terra-toolkit/blob/c5891fb205e45d23f514ea611a5c04290bb3f93a/scripts/aggregate-translations/aggregate-translations.js#L12
* https://github.com/cerner/terra-toolkit/blob/c5891fb205e45d23f514ea611a5c04290bb3f93a/scripts/aggregate-translations/aggregate-translations.js#L14

Then we'll want to add an option like `directories` except have it exclude directories in case translations get aggregated in that are not intended.

**Comment by cody-dot-js** [comment]
Just for clarity, we want it to have both `directories` and `excludes` options?

**Comment by emilyrohrbough** [comment]
@dev-cprice Yes, we need to maintain the directories option for passivity.
