### ISSUE TITLE
Specifying only en-US with aggregate-translations cause it to also generate/look for en translations

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#208]
# Bug Report

## Description
A team that only has en-US translations was trying to use aggregate-translations via CLI. They had used the `-l` flag and passed `['en-US']`, however, aggregate translations was throwing errors that it was unable to find `en` based translations in the specified translations directory

## Steps to Reproduce

1. Set up app with only en-US translations
2. Call aggregate translations via CLI specifying only `en-US` based translations `"aggregate-translations": "tt-aggregate-translations -b ./ -d ./translations -l ['en-US'] -o ./src/aggregated-translations",`
3. See error message about missing `en` based translations

## Additional Context / Screenshots
![screen shot 2018-11-19 at 2 24 18 pm](https://user-images.githubusercontent.com/633148/48733759-2ab27780-ec09-11e8-87a8-648106aca94a.png)

## Expected Behavior
When specifying only needing `en-US` translations with aggregate-translations, it looks for only `en-US` translations

## Environment

* Component Name and Version: terra-toolkit

**Comment by emilyrohrbough** [comment]
@bjankord  This is was intentional implementation. The terra-i18n's fallback strategy uses 'en' as the last fallback locale.

The fallback strategy is:

1. Load country-specific locale if present
2. Fall back to base locale if present
3. Fall back to 'en' if base locale is not present

**Comment by bjankord** [comment]
The en-US.json file was present in the apps `translations` directory. It seems like that meets the first critera, "Load country-specific locale if present". 

It feels buggy that it is falling back to try and load `en` since a criteria match was already made and the fact the user has specified they only have `en-US` translations.

**Comment by emilyrohrbough** [comment]
Yeah I see what you mean, this won't fail the application if 'en' isn't present while translations are aggregated, but this could break their app if the fallback was attempted to be loaded but terra-i18n assumes 'en' is always available.

It is called out in the documentation that 'en' will be added by default if it wasn't included in the specified locales: https://github.com/cerner/terra-toolkit/blob/master/docs/AggregateTranslations.md#aggregate-translations-options
