### ISSUE TITLE
Update to use Node 10

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#214]
# Feature Request

## Description
Node 8.x goes into [Maintenance LTS  mode on 2019-01-01](https://github.com/nodejs/Release#release-schedule). That would be a good time to investigate switching over to Node 10.

**Comment by emilyrohrbough** [comment]
Our current build engine is [`"node": ">=8.9.2"`](
https://github.com/cerner/terra-toolkit/blob/master/package.json#L7). This change would be to bump our minimum to reflect the currently supported node versions. We should have no issues given we are already pulling the latest in Travis CI with this config.

**Comment by emilyrohrbough** [comment]
@ryanthemanuel Do we need to pause on this change given the base node image used internally?

**Comment by emilyrohrbough** [comment]
Closing issue as we've updated to Node 10
