### ISSUE TITLE
Babel Plugin for Class Properties Syntax

### ISSUE THREAD

**Issue by cody-dot-js** [cerner/terra-toolkit#221]
# Feature Request

## Description

It would be nice to have the ability to use the awesome `class properties syntax`. The main benefit desired is the automatic binding of `this` for class methods. It would no longer be necessary to bind this to methods in constructors, e.g.:

```jsx
class Foo extends Component {
  constructor(props) {
    this.state = { ... };
    
    this.handleAction = this.handleAction.bind(this);
  }
  ...
  handleAction(event) {
     const { bar } = this.state;
     ...
  }
  ...
  render () { ... }
}
```
becomes
```jsx
class Foo extends Component {
  constructor(props) {
    this.state = { ... };
  }
  ...
  handleAction = (event) => {
     const { bar } = this.state; // this is automatically bound when using arrow func as class property
     ...
  }
  ...
  render () { ... }
}
```

## Additional Context / Screenshots

* [babel-plugin-transform-class-properties](https://www.npmjs.com/package/babel-plugin-transform-class-properties)

**Comment by bjankord** [comment]
At the time we originally talked through binding techniques for terra-ui, we landing on binding in the constructor as our preferred approach. I'm good with adding this babel plugin and supporting class properties with the toolkit webpack/babel setup. This post was a good read through various ways to handling binding: https://medium.freecodecamp.org/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56

**Comment by emilyrohrbough** [comment]
The babel-loader in our webpack configuration will use the `.babelrc` or `babel.config.js` configuration defined at the root level process run. This can be configured at a project level, so we shouldn't have to make changes to terra-toolkit's webpack config to enable this.

@dev-cprice if you experience differently we can investigate the root cause of the issue
