### ISSUE TITLE
Remove Arabic from list of supported locales

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#229]
# Feature Request

## Description
We are planning to drop Arabic from our list of supported locales. We are unable to get accurate translations at this time. Arabic can still be used by adding it to the list of locales used in the aggregate translations build tool, however, developers will need to supply Arabic translations for any keys that are used in the components they are using. [Doc is being developed](https://github.com/cerner/terra-ui/pull/132) on how to handle this in the terra-ui repo.

**Comment by emilyrohrbough** [comment]
This will be resolved once the aggregate-translations script is moved to the [cerner/terra-aggregate-translations](https://github.com/cerner/terra-aggregate-translations) repo

**Comment by emilyrohrbough** [comment]
In the next MVB we will remove all reference to aggregate-translations and supported locales. For now with the migration to terra-aggregate-translations, the terraSupportedLocales and aggregate-translations script will be available for passivity.
