### ISSUE TITLE
Upgrade raw-loader

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-toolkit#230]
# Feature Request
`raw-loader` released `1.0.0`. We specify [^0.5.1](https://github.com/cerner/terra-toolkit/blob/master/package.json#L99), so we won't pull in the major release. Let's update this

**Comment by emilyrohrbough** [comment]
Similar to: https://github.com/cerner/terra-toolkit/issues/161

**Comment by ryanthemanuel** [comment]
Closing this in lieu of #161
