### ISSUE TITLE
Incorrect Screenshot Naming When Form Factor Testing

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-toolkit#248]
# Bug Report

## Description
For form-factor testing, our screenshot naming always uses the defined form factor as the form directory instead of uses the width for the form directory. If someone changes the viewport size during the test, that screenshot could be incorrectly stored in the wrong form directory.

Code with bug: https://github.com/cerner/terra-toolkit/blob/master/config/wdio/visualRegressionConf.js#L37

## Steps to Reproduce

1. Add example test: https://gist.github.com/emilyrohrbough/2e8f868ae23e82a8c359ade498c8a83e
2. Correct naming, run `FORM_FACTOR=tiny npm run wdio -- --spec tests/wdio/test-spec.js`
3. Incorrect naming, run `FORM_FACTOR=huge npm run wdio -- --spec tests/wdio/test-spec.js`

## Additional Context / Screenshots
Likely a non-passive change, but will be needed to correctly enable form_factor fallback to fix inconsistent viewport sizing. See #137.

## Expected Behavior
Stores screenshot in the form directory of the current viewport width.

## Possible Solution

```diff
function getFormFactor(context) {
-  let formFactor = global.browser.options.formFactor;
+ let formFactor;

-  if (!formFactor) {
    const browserWidth = context.meta.viewport.width;
    const viewportSizes = Object.keys(VIEWPORTS);
    for (let i = 0; i < viewportSizes.length; i += 1) {
      const viewport = viewportSizes[i];
      if (browserWidth <= VIEWPORTS[viewport].width) {
        formFactor = VIEWPORTS[viewport].name;
        break;
      }
    }
- }

  formFactor = formFactor || 'enormous';

  return formFactor;
}

```

## Environment

* Component Name and Version: v4

**Comment by nramamurth** [comment]
@emilyrohrbough I am one step away from opening a PR for this one - https://github.com/cerner/terra-toolkit/commit/221c5e9e0381f4f88df28881c649f2d2b28d0339. Can I go ahead and open it or is there a bigger strategy for this change to go into v5? I could go ahead and fix https://github.com/cerner/terra-toolkit/issues/137 as well if non-passive changes are okay to be opened for review.

**Comment by emilyrohrbough** [comment]
@nramamurth These changes need to wait for v5. at this point I do not think we are ready to start v5 PRs. There will be some overall changes to the repo structure; these changes are relatively smalls so I think the merge conflicts will be harder to resolve if we do the work now vs waiting.

**Comment by nramamurth** [comment]
@emilyrohrbough That sounds good! Thanks.
