### ISSUE TITLE
Update SeleniumDockerService to use docker compose

### ISSUE THREAD

**Issue by mhemesath** [cerner/terra-toolkit#25]
# Issue Description
Selenium docker service should be updated to use docker-compose. This will enable us to create a local hub with as many instances as we want/need. This could have the ability to speed up test runs locall 4-8x

See: http://alexbiddle.github.io/2016/07/04/create-a-selenium-grid-with-docker-compose/

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
This should be handled by including the following within the webdriver config file:
```
const composeFilePath = './compose-file.yml';

seleniumDocker: {
    composeFile: ComposeFilePath;
}

```
And is added to the docker setup [here](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/SeleniumDockerService.js#L29).

However, tests should be added to verify & close this issue.
