### ISSUE TITLE
Aggregate translations cli default options overriding config file

### ISSUE THREAD

**Issue by mschile** [cerner/terra-toolkit#257]
# Bug Report

## Description

tt-aggregate-translations cli default options override the options in the terraI18n.config.js file.

```
const defaultConfig = {
    baseDir: options.baseDir || config.baseDir || process.cwd(),
    directories: options.directories || config.directories || [],
    fileSystem: options.outputFileSystem || config.outputFileSystem || fse,
    locales: options.locales || config.locales || supportedLocales,
    outputDir: options.outputDir || './aggregated-translations',
    excludes: options.excludes || config.excludes || [],
    format: options.format,
  };
```
https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L32

```
const aggregationOption = {
  baseDirectory: commander.baseDir,
  directories: customSearchDirectories,
  exclude: customExcludeDirectories,
  locales: commander.locales,
  outputDir: commander.outputDir,
  configPath: commander.config,
  format: commander.format,
};
```
https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L31

## Steps to Reproduce

1. Create a terraI18n.config.js file and add some configuration
2. Run the aggregate translations cli using only the --config paramenter
3. The default config options override the options in the config file

## Expected Behavior

Config file options take precedence over default options.

## Environment

* Component Name and Version: tt-aggregate-translations v4.23.1
* Browser Name and Version: n/a
* Node/npm Version: Node 8.4.0/Npm 6.7.0
* Webpack Version: n/a
* Operating System and version (desktop or mobile): desktop

**Comment by bjankord** [comment]
Do you have a sample terraI18n.config.js for us to test with? What does the command look like when you run the aggregate translations CLI?

**Comment by mschile** [comment]
Here is config that will illustrate the issue:

terraI18n.config.js
```
const i18nConfig = {
  locales: ['en-US'],
};

module.exports = i18nConfig;
```

Here is the npm script being run:
```
"aggregate-translations": "tt-aggregate-translations",
```

The aggregate translations CLI doesn't output the config but I put in a console.log to output the config.

```
{ baseDir: '/Users/*/Code/demographics',
  directories: [],
  fileSystem: 
   { constants: 
      { O_RDONLY: 0,
        O_WRONLY: 1,
        O_RDWR: 2,
        S_IFMT: 61440,
        S_IFREG: 32768,
        S_IFDIR: 16384,
        ...
     remove: [Function: rimraf],
     removeSync: [Function: rimrafSync] },
  locales: 
   [ 'ar',
     'en',
     'en-US',
     'en-GB',
     'es',
     'es-US',
     'es-ES',
     'de',
     'fi-FI',
     'fr',
     'fr-FR',
     'nl',
     'nl-BE',
     'pt',
     'pt-BR',
     'sv',
     'sv-SE' ],
  outputDir: './aggregated-translations',
  excludes: [],
  format: 'es5' }
```

There is output about which languages are being aggregated and all of the above language are listed instead of the single 'en-US' that was in the config.

```
[terra-toolkit:aggregate-translations] Aggregating translations for ar,en,en-US,en-GB,es,es-US,es-ES,de,fi-FI,fr,fr-FR,nl,nl-BE,pt,pt-BR,sv,sv-SE locales.
```

**Comment by ryanthemanuel** [comment]
The problem here is that we're defining the default in two places: using commander and in the non cli code.  My guess is we should probably just listen to the non cli defaults as a last resort and have no defaults in the commander (where appropriate).

**Comment by nramamurth** [comment]
> My guess is we should probably just listen to the non cli defaults as a last resort and have no defaults in the commander (where appropriate).

@ryanthemanuel I real quick tested the suggestion out and it works as expected. @emilyrohrbough has also listed a few other suggestions on https://github.com/cerner/terra-toolkit/issues/262#issuecomment-472865766. How do we like to approach this problem for v5.0.0?

**Comment by nramamurth** [comment]
I had a second look at @mschile's description - 

> Config file options take precedence over default options.

If the expected behavior is to have the config file take precedence, then I'd believe that flipping the default options in `aggregate-translations.js` could potentially solve the problem. Let me know if this will cause harm.

**Current Defaults:** 

```
const defaultConfig = {
    baseDir: options.baseDir || config.baseDir || process.cwd(),
    directories: options.directories || config.directories || [],
    fileSystem: options.outputFileSystem || config.outputFileSystem || fse,
    locales: options.locales || config.locales || supportedLocales,
    outputDir: options.outputDir || './aggregated-translations',
    excludes: options.excludes || config.excludes || [],
    format: options.format,
  };
```

**Proposed:**

```
const defaultConfig = {
    baseDir: config.baseDir || options.baseDir || process.cwd(),
    directories: config.directories || options.directories || [],
    fileSystem: config.outputFileSystem || options.outputFileSystem || fse,
    locales: config.locales || options.locales || supportedLocales,
    outputDir: options.outputDir || './aggregated-translations',
    excludes: config.exclude || options.exclude || [],
    format: options.format,
  };
```

We could also additionally remove the script defaults as @ryanthemanuel  and @emilyrohrbough  suggested.

**Comment by nramamurth** [comment]
I found another issue with the `exclude` option - the [documentation](https://github.com/cerner/terra-toolkit/blob/master/docs/AggregateTranslations.md#order-of-operations) mentions that the option name is `exclude` and the [aggregate-translations-cli.js](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L27) does correctly parse the argument as `exclude`. The [aggregate-translations.js](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L38) however tries to look for `excludes` property in the config/options which will not exist. 

Isn't it an issue?

**Comment by ryanthemanuel** [comment]
@nramamurth we should fix that as well. Make sure the doc is lined up. I would say let’s change it to excludes since I think more people are using the non cli version of things than the cli version.

**Comment by emilyrohrbough** [comment]
@nramamurth  I would prefer we remove the script default instead of honoring the config file values first. The behavior I would expect if running via the cli script would be that my cli arguments were honored, even if I was using a config file.

> I found another issue with the exclude option

Nice catch on this. +1 to fixing

**Comment by bjankord** [comment]
> I would expect if running via the cli script would be that my cli arguments were honored, even if I was using a config file.

Agreed, that's what I'd expect too.

**Comment by nramamurth** [comment]
@emilyrohrbough @bjankord @ryanthemanuel That sounds good to me, thank you for the update. I shall go ahead and open a PR.
