### ISSUE TITLE
devtool in development should produce original source sourcemaps

### ISSUE THREAD

**Issue by mschile** [cerner/terra-toolkit#258]
# Feature Request

## Description

Currently, devtool is set to 'cheap-source-map' which produces a SourceMap without column-mappings ignoring loader SourceMaps. According to the documentation, this devtool option is only used in special cases [1]. Webpack states the best quality SourceMap for dev is 'eval-source-map' which produces original source SourceMaps.

[1] https://webpack.js.org/configuration/devtool/#special-cases
[2] https://webpack.js.org/configuration/devtool/#development

**Comment by bjankord** [comment]
Yeah, that sounds good. We're open to a PR to update to eval-source-map.

**Comment by lalitha94** [comment]
I would like to work on this.
