### ISSUE TITLE
Update to latest version of axe-core

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#259]
# Feature Request

## Description
We've pinned down axe-core to prevent wdio test failures in dependent projects. We should test updating to the latest axe-core and see if there are any accessiblity issues that are uncovered and then resolves those before we fully update to the latest version of axe-core. When we update, I think we should continue to pin down the version to avoid unexpected accessibility failures as axe-core adds more rules.

## @ Mentions
@emilyrohrbough

**Comment by mjhenkes** [comment]
Maybe we should major version bump terra-toolkit when we unlock axe? I'm thinking it could be very disruptive to our consumers.

**Comment by emilyrohrbough** [comment]
Yeah, I think this is another v5 piece

**Comment by emilyrohrbough** [comment]
Resolved in #285
