### ISSUE TITLE
'exclude' option does not work via CLI as well as via the setup function.

### ISSUE THREAD

**Issue by nramamurth** [cerner/terra-toolkit#264]
# Bug Report

## Description
The [documentation](https://github.com/cerner/terra-toolkit/blob/master/docs/AggregateTranslations.md#order-of-operations) mentions that the option name is `exclude` and the [aggregate-translations-cli.js](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L27) does correctly parse the argument as `exclude`. The [aggregate-translations.js](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L38) however tries to look for `excludes` property in the config/options which will not exist. 

## Steps to Reproduce
1. Use the `exclude` option to glob exclude a set of directories from the search patterns.
2. Notice that the set of directories mentioned in Step 1 are included in the list of directories that are being searched for translations files.

## Expected Behavior
The directories matching the patterns set to the `exclude` option should be excluded from the default search list of directories.

## Possible Solutions
1. Change the option name from `exclude` to `excludes` [here](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L27) and [here](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L34) and update the documentation. For more context, refer to https://github.com/cerner/terra-toolkit/issues/257#issuecomment-474805757. 
2. Keep the documentation and the options as-is and instead update the [line of code](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L38) to look for `exclude` instead of `excludes`. Refer to https://github.com/cerner/terra-toolkit/issues/264#issuecomment-475492131.

## Environment

* Component Name and Version: `terra-toolkit@4.25.0`
* Browser Name and Version: N/A
* Node/npm Version: [e.g. Node 8/npm 5]: Nodejs v8.15.1 AND npm v6.4.1
* Webpack Version: N/A
* Operating System and version (desktop or mobile): Desktop, MacOS. 

## @ Mentions

@emilyrohrbough @ryanthemanuel

**Comment by nramamurth** [comment]
@ryanthemanuel @emilyrohrbough This is with respect to https://github.com/cerner/terra-toolkit/issues/257#issuecomment-474805757. This is an issue irrespective of whether the user is using the CLI version or not and it will be a breaking change if we update `exclude` to `excludes` in the configuration, me thinks. 

What are your thoughts on keeping the configuration options and the documentation as-is and instead update the code below to look for `exclude` instead of `excludes`? The users wouldn't have to update their configuration then.

https://github.com/cerner/terra-toolkit/blob/1015c35decebafad4135c231dd9a2bafdb6f2d8d/scripts/aggregate-translations/aggregate-translations.js#L38

**Comment by emilyrohrbough** [comment]
Normally I am in favor of making passive changes, but I think here it would be fine to make the non-passive change. I do not think anyone has used this option or this bug would have been logged sooner.

If you feel strongly, we could update 
```
excludes: options.exclude || options.excludes || config.excludes || [], 
```
for now and then keep this Issue open to mark as bug fix for MVB.

**Comment by nramamurth** [comment]
I see, I think it should be good to make a non-passive change in that case then. I have made the changes as recommended by Ryan as part of an existing PR https://github.com/cerner/terra-toolkit/pull/265.
