### ISSUE TITLE
Webpack Doesn't Aggregate Locales with Toolkit's Locales

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-toolkit#287]
# Bug Report

## Description
Toolkit's locales use to aggregate `ar`. Updating the `terra-aggreggate-translations` module, `ar` locale was removed. We need add a wrapper around terra-tookit's aggregate-translation script to pass terra-toolkit's locales.

**Comment by ryanthemanuel** [comment]
Closed with #288
