### ISSUE TITLE
Unhandled Promise Rejection in Docker Startup

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-toolkit#30]
# Issue Description
![screen shot 2017-11-28 at 1 25 06 pm](https://user-images.githubusercontent.com/14099737/33339687-981f0e56-d43f-11e7-97a9-0c37c0b6e6d6.png)

**Comment by bjankord** [comment]
By chance when you saw this error, was docker not running? I ran into a similar error after restarting my computer and I didn't have docker running when I was running terra tests.

**Comment by emilyrohrbough** [comment]
This occurred when I killed my nightwatch tests early. I don't think the the instance correctly shutdown and cleaned itself up.

**Comment by mhemesath** [comment]
Can you reproduce this on the hub branch? It changes how containers are managed

**Comment by emilyrohrbough** [comment]
I haven't tested this with the hub branch at all yet

**Comment by emilyrohrbough** [comment]
Unable to reproduce. Closing this issue.
