### ISSUE TITLE
Discuss scoping theme aggregation directories 

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-toolkit#336]
# Feature Request
Theme aggregation will aggregate files within `themes->theme-name` directories.
So as it stands, if someone has theme files within `src` and `lib`, we pull both.

We should discuss scoping this. This change will have to bundled with the next MVB.

**Comment by emilyrohrbough** [comment]
Did we always pull both `src` and `lib`?

**Comment by yuderekyu** [comment]
yes, existing functionality made no distinction
