### ISSUE TITLE
Upgrade axe-core to v3.4.0 or greater

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-toolkit#343]
# Feature Request

## Description
Terra-toolkit currently locks axe-core to 3.2.2. Terra-toolkit should upgrade axe-core to the latest version (3.4.0) to get the latest and greatest features and fixes. However, in order to upgrade to the latest axe-core, there are accessibility violations that need to be addressed.

## Additional Context / Screenshots
Issue #318 is fixed in axe-core 3.4.0. In order for fix the issue, axe-core need to be bumped from 3.2.2 to 3.4.0. We need to evaluated whether or not bumping axe-core will need to be a major version bump for terra-toolkit.

**Comment by gabeparra01** [comment]
@benbcai Would you be able to give an estimate of when this next major version bump would happen for terra-toolkit? My team is releasing our Orion component to testing partners in Q2 and we may need to log the missing browser support in our wdio tests as a risk

**Comment by benbcai** [comment]
@gabeparra01 These are the issues in each of the three monorepos for fixing some of new rules introduced in axe-core-3.3/3.4. PRs are out to address these issues. We are working to identify and fix any remaining accessibility violations in these monorepos.

https://github.com/cerner/terra-core/issues/2716
https://github.com/cerner/terra-framework/issues/941
https://github.com/cerner/terra-framework/issues/945
https://github.com/cerner/terra-clinical/issues/583

**Comment by ryanthemanuel** [comment]
After discussing what the implications of some of these changes are, I think we want to actually disable the new rules that are causing problems with this upgrade to axe-core and make this a minor version bump.
