### ISSUE TITLE
screenshots not taken of Terra-Hookshot Components

### ISSUE THREAD

**Issue by scion976** [cerner/terra-toolkit#348]
# Bug Report
There is an issue in using terra.it.matchesScreenshot() and Terra-Hookshot.  Terra-Hookshit has an onResize prop which gets executed when the screen is resized.  A common usecase is for the popup the close when the user changes the screen size.  It appears that terra.it.matchesScreenshot() also causes this function to run.  If, like in my usecase, the popup closes when the screen resizes then the screenshot causes the popup to close before the snapshot is taken.

## Description
The below example can also be found here:
https://github.cerner.com/UKDevelopment-ClinicalDev/stella-timeline/tree/UKIPDEV-898_newPopup

see:
- src/terra-dev-site/test/Popup/Popup.test.jsx
- test/wdio/Popup/popup.test.js

The test creates. small grey box which opens a hookshot when clicked.  The hookshot has the text "hello".

sample code:
```
import React, { useState, useRef } from 'react';
import Hookshot from 'terra-hookshot';

const Popup = () => {
  const [isPopupOpen, setPopupOpen] = useState(false);
  // const [clickPos, setClickPos] = useState(0);
  const ref = useRef();
  const closePopup = (e) => {
    setPopupOpen(false);
    e.stopPropagation();
  };
  return (
    // eslint-disable-next-line jsx-a11y/click-events-have-key-events,jsx-a11y/no-static-element-interactions
    <div ref={ref} onClick={() => { setPopupOpen(open => !open); }} id="clickMe" style={{ height: '10px', width: '10px', backgroundColor: 'blue', position: 'relative', left: '15em' }}>
      <Hookshot targetRef={() => ref.current} contentAttachment={{ vertical: 'bottom', horizontal: 'center' }} attachmentBehavior="flip" attachmentMargin={5} isEnabled isOpen={isPopupOpen}>
        <Hookshot.Content onEsc={closePopup} onResize={closePopup} onOutsideClick={closePopup}>
          <div style={{ backgroundColor: 'lightgray', padding: '0.25em' }} id="test-hello">
            hello
          </div>
        </Hookshot.Content>
      </Hookshot>
    </div>
  );
};

export default Popup;
```

sample test:
```
describe('Popup Tests', () => {
  before(() => {
    browser.url('#/raw/tests/stella-timeline/popup/popup');
    browser.waitForExist('#clickMe');
    browser.click('#clickMe');
    browser.waitForExist('#test-hello');
  });

  Terra.it.matchesScreenshot();

  it('exists', () => {
    expect($('#test-hello').value).to.exist;
  });
});
```

## Steps to Reproduce

1. Run the test code snippet against the provided code, the tests will fail.  They will pass if the `Terra.it.matchesScreenshot();` is commented out.  Furthermore, when uncommented the screenshot generated does not show the popup despite the test openning the popup.  When the screenshot is commented the 'it' block which checks for the existence of the Hookshot-ed element passes.

## Additional Context / Screenshots
The test will succeed if the onResize prop in Hookshot.Content is removed.

## Expected Behavior
`Terra.it.matchesScreenshot();` should not cause a resize nor alter the page in any way.  I would the snapshot to be completely passive.

## Environment

* Component Name and Version: 
- Terra-toolkit: 5.12.0
- terra-hookshot: ^5.14.0
* Browser Name and Version: terra-toolkit runs tests on chrome
* Node/npm Version: node: 10.16.3, npm: 6.9.0
* Webpack Version: ^4.39.3
* Operating System and version (desktop or mobile): MacOS X, Mojave (v10.14.6)

**Comment by emilyrohrbough** [comment]
What test command are you using to run the test? Also, what is the full spec that you are using to run this? I am curious about the test viewports defined for the full spec and how they are configured.

**Comment by scion976** [comment]
Tests run in the 'huge' form factor and run using this command:
npm run test:wdio -- --spec test/wdio/Popup/popup.test.js

our package.json defines test:wdio as: `"test:wdio": "cross-env NODE_OPTIONS=--max-old-space-size=2048 wdio ./wdio.conf.js",`

Enclosed below is our wdio.conf.js
```
const wdioConf = require('terra-toolkit/config/wdio/wdio.conf');
const webpackConfig = require('./webpack.config');

const config = {
  ...wdioConf.config,

  webpackConfig,
  formFactor: 'huge',
  mochaOpts: {
    compilers: ['js:@babel/register'],
    timeout: 600000,
  },
  terra: {
    selector: '#root', // Global selector required for Terra.it.matchesScreenshot()
  },
  reporters: ['dot', 'spec'],
  reporterOptions: {
    htmlFormat: {
      outputDir: './reports/',
    },
  },
};

exports.config = config;
```

**Comment by emilyrohrbough** [comment]
Is the test example you provided your full spec? Do you have a reduce test case we can reference? I see you've provided a code-snippet. Just wondering if you have something I can pull down myself to test against.

**Comment by scion976** [comment]
You can pull down https://github.cerner.com/UKDevelopment-ClinicalDev/stella-timeline/tree/UKIPDEV-898_newPopup.
That has the code snippets above in the runnable format (just call `npm run test:wdio -- --spec test/wdio/Popup/popup.test.js`).  That popup test is the most trimmed down example which demonstrates the issue.
The real popup I am testing is much more involved but screenshots have been commented out (they were causing subsequent tests to fail since the snapshot closed the popup being tested).  I hope to add them back in later.
If you'd like I'm available to hop on a call, would have be of value?

**Comment by emilyrohrbough** [comment]
Pulled your project down and dug around a bit. The issue you are seeing is actually an implementation detail of the `wdio-screenshot` tool used by the `wdio-visugal-regression-service`.

We use  `checkElement` method provided by `wdio-screenshot` to take element screenshots. This method calls [`makeElementScreenshot`](https://github.com/zinserjan/wdio-screenshot/blob/master/src/modules/makeElementScreenshot.js#L17), which will [trigger a resize event](https://github.com/zinserjan/wdio-screenshot/blob/master/src/modules/beforeScreenshot.js#L16) to "prepare" the element for taking a screenshot. Unfortunately this isn't something we can configure 😞 

The good news, you can organize your tests to take the screenshot last to get around this issue. I have tested the following scenarios:

```js
describe('Popup Tests', () => {
  before(() => {
    browser.url('#/raw/tests/stella-timeline/popup/popup');
    browser.waitForExist('#clickMe');
    browser.click('#clickMe');
    browser.waitForExist('#test-hello');
  });

  it('exists', () => {
    expect($('#test-hello').value).to.exist;
  });

  Terra.it.matchesScreenshot();
});
```
and
```js
describe('Popup Tests', () => {
  before(() => {
    browser.url('#/raw/tests/stella-timeline/popup/popup');
    browser.waitForExist('#clickMe');
    browser.click('#clickMe');
    browser.waitForExist('#test-hello');
  });

  it('exists', () => {
    expect($('#test-hello').value).to.exist;
    Terra.validates.screenshot();
  });
});
```

**Comment by scion976** [comment]
Emily, appreciate quick replies!  Just to make sure I understand, the suggested mitigation ensures that tests depending on the popup won't fail but the screenshots taken will still not have the popup.  Until the 3rd party issue is fixed there is no way to take a screenshot of the popup without disabling the close when onResize is called.

**Comment by emilyrohrbough** [comment]
@scion976 The popup referenced in the migration guide was specific to terra-popup. You have rolled your own popup implementation, so I am unsure of the differences between terra-popup and yours. If you look through the terra-popup tests, it doesn't appear to be hitting this issue: https://github.com/cerner/terra-framework/blob/master/packages/terra-popup/tests/wdio/popup-spec.js#L9

**Comment by scion976** [comment]
The issue was with Hookshot, Terra-Popup uses hookup but only closes if the window width changes: https://github.com/cerner/terra-framework/blob/master/packages/terra-popup/src/Popup.jsx#L174
That may have prevented the error wdio error (the window width may be not be changing), also seems like a good mechanism to mitigate the issue, thanks!

**Comment by emilyrohrbough** [comment]
No problem! Are you okay if we close the issue?

**Comment by scion976** [comment]
I just tested the mitigation technique used by terra-popup and it worked.  Closing the issue and thank you again for your help and quick responses!
