### ISSUE TITLE
Custom axe rules specified in wdio.conf.js are not being reflected/implemented

### ISSUE THREAD

**Issue by avinashg1994** [cerner/terra-toolkit#351]
# Feature Request 

## Description

Axe rules specified in wdio.conf.js are not being reflected/implemented as expected.

## Possible Solution
Merging the global axe rules with the custom axe rules could resolve this issue.

## @ Mentions

@ryanthemanuel @neilpfeiffer

**Comment by emilyrohrbough** [comment]
We already have the ability to configure the axe tool from the wdio config with the `axe.options` key, so we shouldn't need to alter the test framework for this specific use-case. Instead we should provide a custom wdio config for this test run.

The `axe.options` will be picked up by the axe command for each test run: 
https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraCommands/axe-command.js#L64

These options are then used when axe is inject on test page: https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraCommands/axe-command.js#L19

Here is the documentation axe provides for configuring the axe tool: https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#parameters-1

Here are the list of axe rules that can be configured: https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md

Can you try adding a custom wdio config for the `clinical-lowlight-theme` that will disabled the color contrast  rule? It'd look like:

```js
// wdio.conf.js
const defaultConfig = require('terra-toolkit/config/wdio/wdio.conf');
const config = {
    ...defaultConfig,
    axe: {
        inject: true,
        options: {
           rules: [
                 { id: 'color-contrast', enabled: false },
           ],
        },
    }
}
```

**Comment by nramamurth** [comment]
@emilyrohrbough right, that makes sense if the tests need to be run in the Lowlight Theme repository. I am curious, now that all the themes (except for Clinical) are being ported into our mono-repos and the tests are supposed to run for all themes in mono-repos, how will this help? 

Do we supply this custom config when the theme is specifically lowlight in all our repos, maybe?

**Comment by emilyrohrbough** [comment]
@nramamurth you would need to provide the 'lowlight-theme' wdio config for the lowlight test runs.

**Comment by avinashg1994** [comment]
@emilyrohrbough, Thanks for the help and suggestion.
So, As per your https://github.com/cerner/terra-toolkit/issues/351#issuecomment-553474034, I created a custom wdio.conf.js for clinical-lowlight-theme with the suggested additions.
But, I noticed that the rules were not being applied/implemented and the accessibility tests were still being run.
So after having a discussion with @nramamurth, we found that `args` in axeOptions [here](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraCommands/determine-test-options.js#L47-L58) was undefined. So, `const axeRules = options.rules || options.axeRules;` was always empty.

We tried to merge the axe rules from the global object [here](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraCommands/determine-test-options.js#L52) and that seemed to work.
So is the above approach appropriate or is there another way to resolve the same?

**Comment by emilyrohrbough** [comment]
> But, I noticed that the rules were not being applied/implemented and the accessibility tests were still being run.

Was the axe inject itself not applying the rules? I would expect the accessibly tests to run, but to prevent failures for the rules defined in the config. That is what I would have expected given the documentation provided by the Axe tool. 

Can you provide some open-source test examples?

**Comment by nramamurth** [comment]
From what I noticed, the runAccessibilityTest logic in toolkit currently looks for and parses the rules that are explicitly supplied by the consumer (when invoked via isAccessible/validatesElement/itValidatesElement)  and doesn’t consider the rules specified in the config. I could be wrong but maybe we should merge the rules passed in by the consumer on top of the rules provided (if any) in the config.

**Comment by emilyrohrbough** [comment]
Are the rules not being configured when axe is injected?

**Comment by avinashg1994** [comment]
The `axeOptions` being passed to `axe.configure` [here](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraCommands/axe-command.js#L19) does contain the rules which we specified in our custom wdio.conf.js. So i guess it is being injected.
But, the `rules` being passed to `axe.run` [here](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraCommands/axe-command.js#L36-L40) are the rules which we pass to validatesElement or itValidatesElement, which i guess overrides the rules injected using axe.configure.

**Comment by emilyrohrbough** [comment]
thats weird, not how I'd expect it to work. I'd say merging the global rules with the test rule would be fine then
