### ISSUE TITLE
Custom misMatchTolerance is Not Being Honored When Set to 0

### ISSUE THREAD

**Issue by andrewnottaviano** [cerner/terra-toolkit#354]
# Bug Report
## Description

I had a test where the reference screen shot was below the default `misMatchTolerance` so I passed in a `misMatchTolerance: 0` and the test would still not fail. @nramamurth investigated the issue and discovered that there is a bug in the [code](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/TerraCommands/determine-test-options.js#L81) where the passed in `misMatchTolerance` was not applied because I used `0` and `0` is falsey.

See the [Teams conversation](https://teams.microsoft.com/l/message/19:ec7057f0024d451194d19071dc151f86@thread.skype/1573670034777?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1573670034777&teamName=Terra&channelName=Testing%20Support&createdTime=1573670034777) for full details.

## Steps to Reproduce

1. Create a test that should fail due to mismatch but does not because the % difference does not fall below the default `misMatchTolerance`.
2. Pass in the options hash with the option `{ misMatchTolerance: 0 }`
3. Observe the test will still pass despite the custom tolerance

## Expected Behavior

I would expect the test that should fail to start failing when I pass `{ misMatchTolerance: 0 }`
## Possible Solution

See the above linked teams conversation.
## Environment

* Component Name and Version: terra-toolkit v: ^5.9.0
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]: npm v 6.12.0, node v 8.9.2
* Webpack Version: ^4.39.2
* Operating System and version (desktop or mobile): desktop macOS X Mojave

## @ Mentions

@emilyrohrbough @nramamurth

**Comment by emilyrohrbough** [comment]
We should investigate with other numeric values are being honored. We have tests in place that should pass the custom value down: 
https://github.com/cerner/terra-toolkit/blob/master/tests/jest/determine-test-options.test.js#L40

**Comment by emilyrohrbough** [comment]
I think I need more coffee. It was resolving as 'falsy' instead of zero.
