### ISSUE TITLE
Fallback to webpack.config.js devServer entry if config.webpackDevServerConfig is not provided

### ISSUE THREAD

**Issue by mschile** [cerner/terra-toolkit#36]
# Issue Description
The [WebpackDevService](https://github.com/cerner/terra-toolkit/blob/v2.4.0/src/wdio/services/WebpackDevServerService.js#L14) does not support the webpack.config.js [devServer](https://webpack.github.io/docs/configuration.html#devserver) entry.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
The webpack.config.js devServer entry is used as a fallback if config.webpackDevServerConfig is not populated.

## Current Behavior
The webpack.config.js devServer entry is ignored.

**Comment by emilyrohrbough** [comment]
Conversation held on https://github.com/cerner/terra-site/pull/1 which may link.
<img width="671" alt="screen shot 2018-01-30 at 8 35 26 am" src="https://user-images.githubusercontent.com/14099737/35571751-9fd2063c-0598-11e8-9f5d-54be39924d41.png">
Link in comment https://webpack.js.org/configuration/dev-server/#devserver

**Comment by emilyrohrbough** [comment]
The WebpackDevServerService is being deprecated in #81

**Comment by noahbenham** [comment]
Since #81 is merged should this close @emilyrohrbough?
