### ISSUE TITLE
DOS Vulnerability for node-sass - Resolve by Bumping to v ^4.13.1

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-toolkit#384]
# Bug Report

## Description
![Screen Shot 2020-02-14 at 10 24 21 AM](https://user-images.githubusercontent.com/14099737/74548831-31b35d00-4f14-11ea-8831-bc5935b63962.png)
https://www.npmjs.com/advisories/961

Advisory remediation is
> Upgrade to version 4.13.1 or later

**Comment by ryanthemanuel** [comment]
This has been fixed: https://github.com/cerner/terra-toolkit/commit/764dc3e5fae06ce66e6bc59ce85163643cb64d5c#diff-32607347f8126e6534ebc7ebaec4853d
