### ISSUE TITLE
Release Script Check File Access

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-toolkit#4]
terra-toolkit@1.2.1 was release to change permissions to 755 on the executable scripts in src/scripts. The solution was to run `chmod a+x src/scripts/*` to give executable access. When copying files with babel, it will also copy the file permissions. Babel is used in our compile script, so, the read permissions on these src files are the same when compiled to the lib files.

To ensure these permissions remain 755 we should run a check that uses `ls -ld src/scripts/*` to ensure the file permissions of `-rwxr-xr-x` is present on the nightwatch.js, nightwatch-process.js and nightwatch-non-parallel.js.

**Comment by yuderekyu** [comment]
Is this still an issue?

**Comment by mjhenkes** [comment]
I think we can safely say we aren't doing this
