### ISSUE TITLE
Links for installing terra-toolkit needs update

### ISSUE THREAD

**Issue by parthasaradhie** [cerner/terra-toolkit#404]
# Issue Description
The documentation and git header link is pointing to [terra-toolkit-boneyard](https://github.com/cerner/terra-toolkit-boneyard) instead of terra-toolkit

**Comment by StephenEsser** [comment]
@parthasaradhie which links are you referring to?

**Comment by parthasaradhie** [comment]
Here npm install terra-toolkit  is installing terra-toolkit-boneyard instead of this terra-toolkit
https://github.com/cerner/terra-toolkit/blob/master/README.md#getting-started



Here in the header on clicking the link its taking to installation of terra-toolkit-boneyard 
![{9A768254-64B8-4D2E-9DA6-FEE0402866F0} png](https://user-images.githubusercontent.com/12638462/81192079-6d236c00-8fd7-11ea-86c8-c35321e8a688.jpg)

**Comment by StephenEsser** [comment]
This repository was recently repurposed. When you install `terra-toolkit` the installation is coming from code released from `terra-toolkit-boneyard`. 

All code changes to the installable `terra-toolkit` have been moved, and are being made, here: https://github.com/cerner/terra-toolkit-boneyard

This repository is being setup to be a Lerna/Monorepo that will host multiple packages. We'll update the README to try to help make this more clear. This repository no longer hosts the code for the `terra-toolkit` module on npm.
