### ISSUE TITLE
Unlock axe-core version of 2.5 to use latest version

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-toolkit#41]
# Issue Description
Axe was locked to 2.5.0 to prevent wdio test failures in dependent projects.  Once the changes have been made in the dependent projects to handle the latest release with the new accessibility rule of having a landmark defined on a page, we can unlock this dependency.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

## Expected Behavior
Should pull in the latest released version of axe-core (2.6.1 at this time).  Dependent projects (terra-core) should not fail during wdio testing.

**Comment by emilyrohrbough** [comment]
Released in v2.7.0
