### ISSUE TITLE
[eslint-config-terra] Update to ESLint v7.0.0

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-toolkit#411]
# Feature Request

## Description
ESLint 7.0.0 was released. We should look at upgrading. We're currently blocked by projects like airbnb but won't be forever.
https://eslint.org/blog/2020/05/eslint-v7.0.0-released

## Additional Context / Screenshots
Airbnb eslint config v7 issue.
https://github.com/airbnb/javascript/issues/2223

**Comment by ghost** [comment]
Airbnb has included ESLint 7 into their package which now causes eslint-config-terra to throw a dep warning.

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json#L78

![Screen Shot 2020-12-05 at 15 15 49](https://user-images.githubusercontent.com/67115428/101265516-c473f100-370c-11eb-8b6f-96425907acef.png)
