### ISSUE TITLE
[terra-functional-testing] Improve Logger functionality

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-toolkit#414]
# Feature Request

## Description

Improve the functionality of the Logger being developed in the terra-functional-testing library. 

Possible Improvements:

- Add color logging using chalk
- Add logging levels. Debug/Info/Warning/Error
- Add conditional logging for environments. Development/Debug/Production

## Additional Context / Screenshots

This Logger should be considered/discussed if it can/should be reused in other packages.

**Comment by emilyrohrbough** [comment]
We should look into using npmlog. @ryanthemanuel discovered it a week or so back and I like the option to have verbose/silly log level for debugging.

**Comment by StephenEsser** [comment]
Closing. terra-cli introduced a wrapper for npmlog that is consumable by other projects:

https://github.com/cerner/terra-toolkit/pull/460
