### ISSUE TITLE
[eslint-config-terra] Add babel-eslint as the parser

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-toolkit#415]
# Feature Request
Add babel-eslint as the parser for eslint-config-terra to be able to support things like optional chaining.

**Comment by emilyrohrbough** [comment]
I was just about to create this issue. 👍

**Comment by yuderekyu** [comment]
once we make this change, we should remove any instance of us specifying babel-eslint per mono repo
https://github.com/cerner/terra-framework/blob/d0acf51192da891bab488b28497c2754db8511aa/package.json#L54
