### ISSUE TITLE
[terra-open-source-scripts] replace inquirer with prompts

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-toolkit#485]
# Feature Request

Inquirer is a fairly large package. We should replace it with [prompts](https://www.npmjs.com/package/prompts) which is much smaller and fairly similar.

**Comment by emilyrohrbough** [comment]
@ryanthemanuel Was this work done on https://github.com/cerner/terra-toolkit/pull/487?

**Comment by ryanthemanuel** [comment]
Fixed with #487
