### ISSUE TITLE
[terra-toolkit] High Vulnerability in url-regex package

### ISSUE THREAD

**Issue by ghost** [cerner/terra-toolkit#499]
# Bug Report

## Description

Via `npm audit` terra-toolkit's dependencies wdio-visual-regression-service, and post-css-cutom-properties which have dependencies that have a dependency of url-regex.

The vulnerability is "Regular Expression Denial of Service"

There is currently no patch available.

As this is a dev dependency it might be considered low risk.

## Steps to Reproduce

1. `npm i terra-toolkit@^6.0.0`
2. `npm audit`

## Additional Context / Screenshots

![Screen Shot 2020-12-05 at 15 36 30](https://user-images.githubusercontent.com/67115428/101265861-a956b080-370f-11eb-9b72-0a9e37f0666b.png)

https://github.com/kevva/url-regex/pull/74

## Expected Behavior

No vulnerabilities reported.

## Possible Solution

I'm not sure as the maintainer of the package isn't fixing the issue and is pointing people to https://github.com/niftylettuce/url-regex-safe

https://github.com/kevva/url-regex/pull/74

## Environment

* Component Name and Version: terra-toolkit@^6.0.0
* Browser Name and Version: N/A
* Node/npm Version: [e.g. Node 8/npm 5] 10.22.1
* Webpack Ver: N/A

sion:
* Operating System and version (desktop or mobile): MacOS

**Comment by ryanthemanuel** [comment]
This issue will be fixed with our upgrade to WDIO 6 and transition to terra-functional-testing. Also, this is not a huge deal as this is only used in dev dependencies and will never get pulled in to production code
