### ISSUE TITLE
[terra-aggregate-translations] Migrate terra-aggregate translations to terra-toolkit.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-toolkit#521]
# Feature Request

## Description

Migrate [terra-aggregate-translations](terra-aggregate-translations) to terra-toolkit and scope the package name.

Scoping the package name will be a mvb but in name only, the @cerner/terra-aggregate-translations package should be functionally passive with terra-aggregate-translations package.

This feature is blocked by PR: [#33](https://github.com/cerner/terra-aggregate-translations/pull/33) which must be completed first.

The new scoped package should be consumed by webpack-config-terra.

**Comment by StephenEsser** [comment]
Closing, this work was completed in https://github.com/cerner/terra-toolkit/pull/549
