### ISSUE TITLE
Create skeleton for package-json-lint package

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-toolkit#538]
# Story

## Description

As a developer of terra, I want to have a skeleton package package-json-lint that will be used to flag problems that are present in a package.json

## Motivation

So that I can start developing that linter for teams

## Definition of Done

We'll know we're done when:

* The package is created is merged to main and the overall build for terra-toolkit succeeds
* The package is not configured to release

**Comment by StephenEsser** [comment]
+1
