### ISSUE TITLE
Match Screenshot doesn't use name argument when just one argument is specified.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-toolkit#54]
# Issue Description
In https://github.com/cerner/terra-toolkit/commit/195e65a1d29859a04f0df695bedd4c515381cba2, I refactored the function to use an array of arguments and check the length of that array to see if the developer wanted to use a name, a hash, or both for checking theming. However, this refactor prevents matchScreenshot from reading in the name if it's the only argument.

Steps to Replicate.
1. Write the code `Terra.should.matchScreenshot('1');` for a screenshot test.

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
It creates a screenshot named "1".

## Current Behavior
It skips the name argument, and produces a screenshot with the name "default".

**Comment by emilyrohrbough** [comment]
@JakeLaCombe I actually fixed this in #49. This is available in the v2.7.0 released 1/29/18.

**Comment by JakeLaCombe** [comment]
thanks! We can close this then
