### ISSUE TITLE
[terra-functional-testing] Allow filtering tests based on theme and locale

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-toolkit#579]
# Feature Request

## Description

Several consumers have requested the ability to run only a subset of their tests in a theme or locale. This can be accomplished today via excludes and suites, but it tends to run counter to our terra test runner because it breaks any sort of looping the test runner tries to do.

We do currently have the ability to filter viewports via our `terra.describeViewports` helper that loops through viewports and will allow you to run a group of tests at only one.

#### Proposal
Create a new helper `terra.describeTests`. (I'm open to name suggestions). Instead of taking an array of viewports the helper should take an object. 

```javascript
Terra.describeTests(
  'search',
  {
    viewports: ['tiny', 'huge'],
    locales: ['en', 'es'],
    themes: ['terra-default-theme', 'clinical-lowlight-theme'],
  }, 
  () => {
  it('checks accessibility', () => {
    Terra.validates.element('checks a11y');
  });
});
```

The helper would blow out the tests to be run through all permutations of the variables. So in the case of the example above would run the check accessibility test 8 times. viewports would be switched with the set window command, locales would be switched via the setApplicationLocale command and we would have to add a setApplicationTheme command to switch the theme.

These would all be run within a single build of an application. Viewports, locales, and themes should each have a single default (ex. huge, en, terra-default-theme). This is different from today where `describeViewports` runs through all viewports if none are defined.

The terra wdio test runner has cli options to set the locale, theme, and viewport. If these are set only those tests should be run. For example if en, and tiny were set the above test would run twice, once for each command.

IE considerations: IE does not support dynamic theme switching. To allow different themes to be run in IE we will have to rely on building the site twice, once for each theme and running the full suite of tests for the number of themes requested. To indicate this, there should be a cli command for the test runner. `--IEThemeMode`, again, i'm open to suggestions on names.

## Additional Context / Screenshots

Evaluation of the exclude and suite options:
 
For arguments sake lets say we have 3 tests:
 
Test A - A normal test you want to run in any theme.
Test B - A logic only test that you don't need to run in any theme besides the default.
Test C - A test that should only be run in lowlight.
 
### using Suites only:
I'm assuming you can use globs in the suites.
#### Config
```javascript
suites: {
  theme: [
    Test A //'./tests/wdio/theme/**/*-spec.js',
  ],
  lowlight: [
    Test C //'./tests/wdio/lowlight/**/*-spec.js',
  ],
  other: [
    Test B //'./tests/wdio/other/**/*-spec.js',
   ],
 },
```
 
#### Commands

`terra wdio --suite theme --suite other`

`terra wdio --themes clinical-lowlight --suite theme --suite lowlight`

Downside is that  these would fail. You can't run all tests at once or all themes in a single call.

`terra wdio`

`terra wdio --themes clinical-lowlight terra-default-theme`

 
### using exclude:
No config changes. I'm assuming you can glob exclude.
#### Commands

`terra wdio --exclude './tests/wdio/lowlight/**/*-spec.js'`

`terra wdio --themes clinical-lowlight --exclude './tests/wdio/other/**/*-spec.js',`

Same downsides as suites, I like suites better.
 
#### separate config:
this option breaks out the lowlight tests into it's own wdio.conf.js file
wdio.conf.js
```javascript
const { config } = require('@cerner/terra-functional-testing/lib/config/wdio.conf');
config.exclude = ['./tests/wdio/lowlight/**/*-spec.js',];


exports.config = config;
```
wdio.lowlight.conf.js
```javascript
const { config } = require('@cerner/terra-functional-testing/lib/config/wdio.conf');
config.exclude = ['./tests/wdio/other/**/*-spec.js',];

exports.config = config;
```
#### commands

`terra wdio`

`terra wdio --config wdio.lowlight.conf.js --themes clinical-lowlight`

Downsides 
this command still breaks

`terra wdio --themes clinical-lowlight terra-default theme`

None of these options really feel great and none really seem to mesh well with our test runner with regards to theme and locale, Does anyone have any other ideas or suggestions about how we could set this up? These scenarios do get a little simpler with the exclusion of test c, but we still would not be able to use our test runner because you cannot scope suites or excludes to a specific theme run. This work might be easier if we excluded IE and were able to dynamic theme switch within tests instead of running the test twice, one could write a test for either lowlight or for the default theme within the same spec file. but ie isn't going  anywhere soon.

**Comment by benbcai** [comment]
- This issue is separated into two parts.
  -  First part - Filter tests based on form factors, locales, and themes.
  - Second part - Support dynamic theme and locale switching to run tests for all permutations based on these options.
