### ISSUE TITLE
[terra-functional-testing] Add error screenshot reporting

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-toolkit#594]
# Feature Request

## Description

Add functionality to capture a screenshot if an error occurs during the test run.

## Additional Context / Screenshots

WebDriverIO v4 supported a `screenshotPath` option that would log a screenshot if a command failed.

```
// Saves a screenshot to a given path if a command fails.
screenshotPath: 'shots',
```

This option has been [removed](https://github.com/webdriverio/webdriverio/commit/5f3432805ec4a8ce94e13c25ddf7e29f09a3337c) in WebDriverIO v5/6. Their recommendation is for consumers to implement the screenshot reporting themselves. A few example can be found [here](https://github.com/webdriverio/webdriverio/issues/3388).

This issue should add functionality to automatically capture a screenshot if an error occurs during the test run. For now, the path should not be configurable. The path should always output `error` along side `reference`, `latest`, and `diff` in the snapshots folder. 

```
.
├── __snapshots__
│   ├── diff
│   ├── error
│   ├── latest
│   └── reference
```

**Comment by benbcai** [comment]
One additional recommendation we talked about is to clear the `error` folder before each test run since those error screenshots will no longer be relevant for the next run.

**Comment by benbcai** [comment]
> One additional recommendation we talked about is to clear the `error` folder before each test run since those error screenshots will no longer be relevant for the next run.

It was decided that clearing the `error` folder will be done on #620 together with clearing the `latest` and `diff` folders.
