### ISSUE TITLE
[terra-functional-testing] Configurable webpack file path

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-toolkit#604]
# Feature Request

## Description
webpack.config.js is currently always being [read from the root directory](https://github.com/cerner/terra-toolkit/blob/28f4e2d9c0339b01db3a70990f66e187e56835c1/packages/terra-functional-testing/tests/jest/config/utils/getConfigurationOptions.test.js#L26). Add an option to allow reading webpack.config.js from a different path.

**Comment by mjhenkes** [comment]
We should wait on this feature until we have a solid consumer use case.
