### ISSUE TITLE
[terra-functional-testing] Spike on upgrading to WebDriverIO v7

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-toolkit#612]
# Story

## Description
As a developer I want to spike on upgrading terra-functional-testing to WebDriverIO v7 (#585)

## Motivation
So that we know how much work effort is needed and what the breaking changes are if any.

## Definition of Done

We'll know we're done when there is a summary listing what work is needed and log issues describing what changes are needed.

**Comment by benbcai** [comment]
### WebdriverIO v7 Spike Summary

#### Notable features introduced in v7: [Release notes](https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/)
- Impacts
   - The majority of the changes in V7 mainly only impact TypeScript projects as the code base has all moved to TypeScript. It also upgraded to Cucumber V7 and affects projects using Cucumber as some of the Cucumber hooks have changed. The impact on terra-functional-testing is minimal since it doesn't have TypeScript or use Cucumber.
- [Node Version Support](https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/#drop-node-v10-support)
   - Support for Node 10 has dropped and recommends to be on Node 14 or higher. Testing was done using [terra-core](https://github.com/cerner/terra-core), [terra-framework](https://github.com/cerner/terra-framework), and [terra-clinical](https://github.com/cerner/terra-clinical) running V7 on Node 12 and no issues were found.
- [Test Coverage Report](https://github.com/cerner/terra-toolkit/issues/625)
   - The existing [@wdio/devtool-service](https://www.npmjs.com/package/@wdio/devtools-service) now offers a new report that captures test coverage. There are assertion APIs that can be used to assert that a certain percentage of coverage in a source file is met.
- Upgrade Path
  - The upgrade path for terra-functional-testing to upgrade to WDIO 7 would be the following
    - Major version bump on terra-functional-testing
    - Upgrade all [@wdio dependency packages](https://github.com/cerner/terra-toolkit/blob/79469da47af9f91acec4354c490bcb506c63739f/packages/terra-functional-testing/package.json#L49-L54) to latest V7 versions.
    - Drop Node 10 support.
- The following new features are also provided in V7. Terra-functional-testing currently may not have any need or interest in taking advantage of features.
   - [Google Lighthouse Integration](https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/#improved-google-lighthouse-integration)
   - [PWA Check Command](https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/#new-pwa-check-command)
   - [Auto Compiling](https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/#auto-compiling)
   - [W3C Protocol Compliance](https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/#stricter-protocol-compliance)

**Comment by mjhenkes** [comment]
+1
