### ISSUE TITLE
Handle i18n in terra-toolkit

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-toolkit#69]
# Issue Description

Create the ability to test different locales within terra-toolkit.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

We will want this to work in combination with parallelization.  Since we can't do this in Travis (you have to pay), and we want to limit resources, we will want the parallelization to be handled via running a very specific combination (e.g. pt-BR and small form factor) and then let the build system (e.g. jenkins) handle the parallelization.

## Current Behavior

N/A

**Comment by emilyrohrbough** [comment]
With the enhancement to support locale, we will want to organize screenshots by locales as well. This will results in a MVB of terra-toolkit as screenshots will be stored in a new location. 
With this, enhancements being made are:
1. Organize screenshot by `locale`, then `browser`
2. Have a feature to shorten long screenshots name via the use of `[]` in the context 
3. Organize screenshots by spec file

This results in the screenshot pattern of:
```screen/locale/browser/test_suite/test_parent[test_name].widthxheight.png```

The current screenshot pattern is:
```screen/browser/test_parent[test_name].widthxheight.png```

Example:
```
// example-spec.js
describe('This is a long screenshot name for an [example test], () => {
      Terra.should.matchScreenshot();
});
```
Proposed naming result
```reference/en/chrome/example/example_test[default]..470x768.png```

Current naming result
```reference/chrome/This_is_a_long_screenshot_name_for_an_[example_test][default]..470x768.png```

**Comment by emilyrohrbough** [comment]
### Changes
Add the wdio config key `locale` to take a single test locale value with the default value being 'en'.  This `locale` value will be used by the ServeStatic service to set the lang attribute on the site. Also, the default visual regression config will use the `locale` value to save the screenshots in the locale specific directory (see previous comment).

Toolkit will not be responsible for paralyzation itself, as this is required by the build system. Given paralyzation will be handled by the build system, to created paralyzed locale runs, multiple webdriver configuration will need to be provided for each form-factor. In these configs, unique `port` and `locale` values will be needed for the `n` instances of the StaticServe service to start correctly.
