### ISSUE TITLE
Error using dev build due to webpack config terra

### ISSUE THREAD

**Issue by bizsuggestworks** [cerner/terra-toolkit#721]
I am trying to build the project using npm run build:dev && webpack-dev-server

I am getting this error 

`[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'stats'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, static?, watchFiles?, webSocketServer? }`

so when i digged further found that its not liking the stats keyword 
https://github.com/cerner/terra-toolkit/blob/5035b4fae47f4ec32189048f7cd90baa85d0b041/packages/webpack-config-terra/src/webpack.config.js#L240

**Comment by benbcai** [comment]
An internal issue has been logged to investigate the effort and impact are to fix this.

**Comment by benbcai** [comment]
Duplicate of #719
