### ISSUE TITLE
[duplicate-package-checker-webpack-plugin] Support node 16

### ISSUE THREAD

**Issue by wuifdesign** [cerner/terra-toolkit#730]
# Bug Report

## Description
Currently `duplicate-package-checker-webpack-plugin` has following entry in the `package.json`.

https://github.com/cerner/terra-toolkit/blob/b947af08ca377bb6094628005af428314f7adcb3/packages/duplicate-package-checker-webpack-plugin/package.json#L6-L8

I think node 16 can be added safely otherwise you will get the following error on install:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@cerner/duplicate-package-checker-webpack-plugin@2.2.0',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^14.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.4.1' }
npm WARN EBADENGINE }
```

**Comment by boris-petrov** [comment]
Node 17 also.

**Comment by wuifdesign** [comment]
maybe just this?

```
"node": "10 || 12 || 14 || >=16" 
```

**Comment by benbcai** [comment]
@wuifdesign Thanks for reporting this issue. We will revert the change and get it released.
