### ISSUE TITLE
Add a Screenshot Grabbing Utility

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-toolkit#9]
# Issue Description
We need to add the ability to capture screenshots.  There's a lot of potential here, and this may need to be split up into several issues, but for documentation purposes the functionality we would like to have is:

* A screenshot grabber that captures screenshots
* Some mechanism to compare screenshots against an "official version"

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
The following pieces are needed:
- [ ] Ability to capture screenshot and compare
- [ ] Script to handle obsolete snapshots
- [ ] Script to handle snapshot management (i.e. stale snapshots)

**Comment by emilyrohrbough** [comment]
#### Proposed Snapshot File Structure:
``` __snapshots__/locale/browser/snapshot-name```

#### Proposed Snapshot Name:
```ExampleName.TestId.SnapshotName.BrowserSize```

- TestID is identified via the test step name as the test step number inclosed in brackets. If a test step number is not provided, fallback to use test step name.

- Snapshot Name is an optional unique name to describe the particular instance of a test step. For example, 'Selected' or 'Disclose'. Defaults to the name 'Default'.

**Comment by emilyrohrbough** [comment]
Resolved in #18.
