### ISSUE TITLE
Unable to install terra-toolkit 

### ISSUE THREAD

**Issue by kevinmanase** [cerner/terra-toolkit#96]
# Issue Description
I'm on Windows but using a Linux Subsystem for my React dev environment. I keep getting some kind of EINVAL -22 error 💣. The screenshot below says aggregate-translations.js but it also complains about other things in that bin folder.
![image](https://user-images.githubusercontent.com/7396751/39530511-bd334c88-4dee-11e8-8e9f-f2fbeb98b914.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

It should be installed in peace.👍

## Current Behavior

N/A

## Steps to Reproduce

1. Open terminal 💻
2. Run <code>npm install terra-toolkit --save-dev</code> ⛏
3. Errors out after in the middle of the installation 💣

## Environment

* Component Version: 3.2.0
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): Desktop Windows 10, Linux Subsystem
* Node: v10.0.0
* npm: 5.6.0

**Comment by mjhenkes** [comment]
Issue resolved: The problem was with an outdated version of npm 3.x We upgraded to 5.x and npm installed correctly.

**Comment by mjhenkes** [comment]
JK, still a problem

**Comment by radiant-tangent** [comment]
Is there any news or a workaround for this?  I'm encountering similar errors around terra-i18n aggregate translation with the linux subsystem on windows.

**Comment by mjhenkes** [comment]
Could you try the latest terra toolkit? We thought the solution might be removeing ./'s from the binaries in terra-toolkit but @kevb10 was unable to verify.

**Comment by mjhenkes** [comment]
And make sure you're using aggregate translations from terra-toolkit, not terra-i18n. That one still has the ./'s

**Comment by emilyrohrbough** [comment]
I notice you npm v5.6.0. We are using npm v8.9.2. Can you upgrade your version and try install again?

**Comment by emilyrohrbough** [comment]
I notice your node version is v10.0.0. We are currently using v8.9.2. Can you try downgrading to see if this is resolved?

**Comment by radiant-tangent** [comment]
I don't see where it says I'm using node  v10.0.0.  I am using 8.11.2.

**Comment by radiant-tangent** [comment]
I receive the same error with 8.9.2 https://gist.github.com/gumaste/2a39b454424c3a5ac34b85db04384ede

**Comment by kevinmanase** [comment]
PR #99 didn't fix the issue 😢

**Comment by emilyrohrbough** [comment]
@kevb10 @gumaste I have made changes in #113 with @BenBoersma who has a windows device.
After reading https://msdn.microsoft.com/en-us/library/ms832054.aspx it was thought the install failures is occuring due to the `:` in our bin script naming (tt:serve, tt:aggregate-translations, tt:serve-static). Ben has been able to verify these changes allow for a successful install on his device, but would you mind pulling the `i18n-locale-testing-tt-v3` branch to verify as well?
